version: "3"
services:
  celery:
    build:
      context: .
    container_name: cube_python_celery_celery
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine3.18
    container_name: cube_python_celery_redis
    ports:
      - "6379:6379"
